- name: add telegraf apt-key
  apt_key: 
    url: https://repos.influxdata.com/influxdb.key 
    state: present 
  become: yes

- name: add telegraf apt repository
  apt_repository: 
    repo: 'deb https://repos.influxdata.com/debian stretch stable' 
    state: present 
    filename: telegraf 
    update_cache: yes
  become: yes

- name: install telegraf
  apt: 
    name: telegraf
    state: present
    update_cache: yes
  become: yes

- name: Get Influx URL
  shell: "kubectl get services | grep influx | awk '{ print $3}'"
  register: influx_fact

- set_fact: 
    influxUrl: "{{ influx_fact.stdout }}"
    run_once: true

- name: Copy telegraf config
  template:
    src: templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  become: yes

- name: Copy k8s plugin
  copy:
    src: templates/k8s.conf
    dest: /etc/telegraf/telegraf.d/k8s.conf
  become: yes

- name: Start telegraf daemon
  service:
    name: telegraf
    enabled: yes
    state: started
  become: yes